#  model information
#  - name: model name, used for display
#    task: model task, used for display
#    input_size: input size, used for display
#    folder: which folder the model located in, used for jumping to model detail
#    acceptable_time: maximum acceptable inference time, large ones will be marked red
#    keyword: used to specify this model from all benchmark results
#
#  device information
#  - name: full device name used to identify the device block, and jump to device detail
#    display_info: device information for display
#    platform: used to identify benchmark result of specific platform
#
#  suffix information
#  - model: which model
#    device: which device
#    suffix: this suffix will be appended to end of this text

Models:
  - name: "YuNet"
    task: "Face Detection"
    input_size: "160x120"
    folder: "face_detection_yunet"
    acceptable_time: 50
    keyword: "face_detection_yunet"

  - name: "SFace"
    task: "Face Recognition"
    input_size: "112x112"
    folder: "face_recognition_sface"
    acceptable_time: 200
    keyword: "face_recognition_sface"

  - name: "FER"
    task: "Face Expression Recognition"
    input_size: "112x112"
    folder: "facial_expression_recognition"
    acceptable_time: 200
    keyword: "facial_expression_recognition_mobilefacenet"

  - name: "LPD_YuNet"
    task: "License Plate Detection"
    input_size: "320x240"
    folder: "license_plate_detection_yunet"
    acceptable_time: 700
    keyword: "license_plate_detection_lpd_yunet"

  - name: "YOLOX"
    task: "Object Detection"
    input_size: "640x640"
    folder: "object_detection_yolox"
    acceptable_time: 2800
    keyword: "object_detection_yolox"

  - name: "NanoDet"
    task: "Object Detection"
    input_size: "416x416"
    folder: "object_detection_nanodet"
    acceptable_time: 2000
    keyword: "object_detection_nanodet"

  - name: "PPOCRDet-CN"
    task: "Text Detection"
    input_size: "640x480"
    folder: "text_detection_ppocr"
    acceptable_time: 2000
    keyword: "text_detection_cn_ppocrv3_2023may"

  - name: "PPOCRDet-EN"
    task: "Text Detection"
    input_size: "640x480"
    folder: "text_detection_ppocr"
    acceptable_time: 2000
    keyword: "text_detection_en_ppocrv3_2023may"

  - name: "CRNN-EN"
    task: "Text Recognition"
    input_size: "100x32"
    folder: "text_recognition_crnn"
    acceptable_time: 2000
    keyword: "text_recognition_CRNN_EN"

  - name: "CRNN-CN"
    task: "Text Recognition"
    input_size: "100x32"
    folder: "text_recognition_crnn"
    acceptable_time: 2000
    keyword: "text_recognition_CRNN_CN"

  - name: "PP-ResNet"
    task: "Image Classification"
    input_size: "224x224"
    folder: "image_classification_ppresnet"
    acceptable_time: 1000
    keyword: "image_classification_ppresnet50"

  - name: "MobileNet-V1"
    task: "Image Classification"
    input_size: "224x224"
    folder: "image_classification_mobilenet"
    acceptable_time: 500
    keyword: "image_classification_mobilenetv1"

  - name: "MobileNet-V2"
    task: "Image Classification"
    input_size: "224x224"
    folder: "image_classification_mobilenet"
    acceptable_time: 500
    keyword: "image_classification_mobilenetv2"

  - name: "PP-HumanSeg"
    task: "Human Segmentation"
    input_size: "192x192"
    folder: "human_segmentation_pphumanseg"
    acceptable_time: 700
    keyword: "human_segmentation_pphumanseg"

  - name: "WeChatQRCode"
    task: "QR Code Detection and Parsing"
    input_size: "100x100"
    folder: "qrcode_wechatqrcode"
    acceptable_time: 100
    keyword: "WeChatQRCode"

  - name: "YoutuReID"
    task: "Person Re-Identification"
    input_size: "128x256"
    folder: "person_reid_youtureid"
    acceptable_time: 800
    keyword: "person_reid_youtu"

  - name: "MP-PalmDet"
    task: "Palm Detection"
    input_size: "192x192"
    folder: "palm_detection_mediapipe"
    acceptable_time: 500
    keyword: "palm_detection_mediapipe"

  - name: "MP-HandPose"
    task: "Hand Pose Estimation"
    input_size: "224x224"
    folder: "handpose_estimation_mediapipe"
    acceptable_time: 500
    keyword: "handpose_estimation_mediapipe"

  - name: "MP-PersonDet"
    task: "Person Detection"
    input_size: "224x224"
    folder: "person_detection_mediapipe"
    acceptable_time: 1300
    keyword: "person_detection_mediapipe"

  - name: "MP-Pose"
    task: "Pose Estimation"
    input_size: "256x256"
    folder: "pose_estimation_mediapipe"
    acceptable_time: 700
    keyword: "pose_estimation_mediapipe"

  - name: "VitTrack"
    task: "Object Tracking"
    input_size: "1280x720"
    folder: "object_tracking_vittrack"
    acceptable_time: 1000
    keyword: "object_tracking_vittrack"


Devices:
  - name: "Intel 12700K"
    display_info: "Intel\n12700K\nCPU"
    platform: "CPU"

  - name: "Atlas 200I DK A2"
    display_info: "Atlas 200I DK A2\nAscend 310B\nCPU"
    platform: "CPU"

  - name: "Atlas 200 DK"
    display_info: "Atlas 200 DK\nAscend 310\nCPU"
    platform: "CPU"

  - name: "Khadas VIM3"
    display_info: "Khadas VIM3\nA311D\nCPU"
    platform: "CPU"

  - name: "Khadas VIM4"
    display_info: "Khadas VIM4\nA311D2\nCPU"
    platform: "CPU"

  - name: "Khadas Edge2 (with RK3588)"
    display_info: "Khadas Edge2\nRK3588S\nCPU"
    platform: "CPU"

  - name: "Jetson Nano B01"
    display_info: "Jetson Nano\nB01\nCPU"
    platform: "CPU"

  - name: "Jetson Nano Orin"
    display_info: "Jetson Nano\nOrin\nCPU"
    platform: "CPU"

  - name: "Raspberry Pi 4B"
    display_info: "Raspberry Pi 4B\nBCM2711\nCPU"
    platform: "CPU"

  - name: "Horizon Sunrise X3 PI"
    display_info: "Horizon Sunrise Pi\nX3\nCPU"
    platform: "CPU"

  - name: "MAIX-III AX-PI"
    display_info: "MAIX-III AX-Pi\nAX620A\nCPU"
    platform: "CPU"

  - name: "Toybrick RV1126"
    display_info: "Toybrick\nRV1126\nCPU"
    platform: "CPU"

  - name: "StarFive VisionFive 2"
    display_info: "StarFive VisionFive 2\nStarFive JH7110\nCPU"
    platform: "CPU"

  - name: "Jetson Nano B01"
    display_info: "Jetson Nano\nB01\nGPU"
    platform: "GPU (CUDA-FP32)"

  - name: "Jetson Nano Orin"
    display_info: "Jetson Nano\nOrin\nGPU"
    platform: "GPU (CUDA-FP32)"

  - name: "Khadas VIM3"
    display_info: "Khadas VIM3\nA311D\nNPU"
    platform: "NPU (TIMVX)"

  - name: "Atlas 200 DK"
    display_info: "Atlas 200 DK\nAscend 310\nNPU"
    platform: "NPU (CANN)"

Suffixes:
  - model: "MobileNet-V1"
    device: "Khadas VIM3"
    platform: "NPU (TIMVX)"
    str: "\\*"

  - model: "MobileNet-V2"
    device: "Khadas VIM3"
    platform: "NPU (TIMVX)"
    str: "\\*"
