Benchmark:
  name: "Face Detection Benchmark"
  data:
    type: "Detection"
    path: "benchmark/data/face/detection"
    files: ["group.jpg", "concerts.jpg", "dance.jpg"]
    sizes: # [[w1, h1], ...], Omit to run at original scale
      - [160, 120]
      - [640, 480]
  metric:
    type: "Detection"
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "YuNet"
  modelPath: "models/face_detection_yunet/face_detection_yunet_2021sep.onnx"
  confThreshold: 0.6
  nmsThreshold: 0.3
  topK: 5000