Data:
  name: "Images for Face Detection"
  url: "https://drive.google.com/u/0/uc?id=1lOAliAIeOv4olM65YDzE55kn6XjiX2l6&export=download"
  sha: "0ba67a9cfd60f7fdb65cdb7c55a1ce76c1193df1"
  filename: "face_detection.zip"
  parentPath: "benchmark/data"

Benchmark:
  name: "Face Detection Benchmark"
  parentPath: "benchmark/data/face_detection"
  fileList:
    - "group.jpg"
    - "concerts.jpg"
    - "dance.jpg"
  backend: "default"
  target: "cpu"
  sizes: # [w, h], Omit to run at original scale
    - [160, 120]
    - [640, 480]
  repeat: 100 # default 100

Model:
  name: "YuNet"
  modelPath: "models/face_detection_yunet/face_detection_yunet.onnx"
  confThreshold: 0.6
  nmsThreshold: 0.3
  topK: 5000
  keepTopK: 750