Benchmark:
  name: "Human Segmentation Benchmark"
  type: "Base"
  data:
    path: "data/human_segmentation"
    files: ["messi5.jpg", "100040721_1.jpg", "detect.jpg"]
    sizes: [[192, 192]]
    toRGB: True
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "PPHumanSeg"
