Benchmark:
  name: "Image Classification Benchmark"
  data:
    type: "ClassificationImageLoader"
    path: "benchmark/data/image_classification"
    files: ["coffee_mug.jpg", "umbrella.jpg", "wall_clock.jpg"]
    sizes: [[256, 256]]
    toRGB: True
    centerCrop: 224
  metric:
    type: "Base"
    warmup: 30
    repeat: 10
    reduction: "median"
  backend: "default"
  target: "cpu"

Model:
  name: "PPResNet"
  modelPath: "models/image_classification_ppresnet/image_classification_ppresnet50_2021oct.onnx"
  labelPath: "models/image_classification_ppresnet/imagenet_labels.txt"