Benchmark:
  name: "Person ReID Benchmark"
  type: "Base"
  data:
    path: "data/person_reid"
    files: ["0030_c1_f0056923.jpg", "0042_c5_f0068994.jpg", "0056_c8_f0017063.jpg"]
    sizes: [[128, 256]]
  metric:
    warmup: 30
    repeat: 10
  backend: "default"
  target: "cpu"

Model:
  name: "YoutuReID"
